name: Monorepo CI

on:
    push:
        branches: [ master ]
    pull_request:
        types: [ synchronize, opened, ready_for_review, reopened ]
        branches: [ master ]


env:
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    GITHUB_TOKEN: ${{ github.token }}
    BASE_BRANCH: ${{ github.event_name == 'pull_request' && 'refs/remotes/origin/master' || github.event.before }}

# Cancel running jobs on subsequent pushes to the same PR or branch.
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    install-dependencies:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
                node_version:
                    - 12
                    - 14
                    - 16
                architecture:
                    - x64
                # an extra windows-x86 run:
                include:
                    -   os: windows-2016
                        node_version: 12
                        architecture: x86
        name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: '18'
                    cache: 'yarn'
            -   run: yarn install --frozen-lockfile
            -   name: Run Build
                run: yarn build
            -   name: Run Lint
                run: yarn lint

    ci-lint:
        name: Monorepo CI - Lint
        runs-on: ubuntu-latest
        needs: install-dependencies
        if: github.event_name == 'pull_request'
        steps:
            -   name: Checkout Branch
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            -   uses: actions/setup-node@v3
                with:
                    node-version-file: 'package.json'
                    cache: 'yarn'
            -   name: Install Dependencies
                run: yarn install --frozen-lockfile
            -   name: Run Build
                run: yarn build
            -   name: Run Lint
                run: yarn lint
            -   name: Run Tests
                run: yarn test
